version: "3.7"

services: 
  # register-company-dev:
  #   build: .
  #   ports:
  #     - 3000:3000
    # volumes:
    #   - ./:/app
    # command: npm run dev
  # openligo:
  #   build: .
  #   ports:
  #     - 3000:3000